name: Publish
on:
  workflow_dispatch:
    branches:
      - 'master'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: starter
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Conventional Changelog Action
        id: changelog 
        uses: TriPSs/conventional-changelog-action@v3 
        with: 
            github-token: ${{ secrets.GITHUB_TOKEN }}
            output-file: "./src/CHANGELOG.md"
            version-file: package.json, package-lock.json
      - uses: fregante/setup-git-user@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev librsvg2-dev libayatana-appindicator3-dev

      - name: Rust setup
        uses: dtolnay/rust-toolchain@stable

      - name: Rust cache
        uses: swatinem/rust-cache@v2
        with:
          workspaces: './src-tauri -> target'      

      - name: Sync node version and setup cache
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'yarn'

      - name: Install app dependencies and build web
        run: | 
          yarn
          npx update-browserslist-db@latest

      - name: Build the app
        uses: tauri-apps/tauri-action@v0
          
      - uses: "softprops/action-gh-release@v1"
        with:
          token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          draft: false
          tag_name: ${{ steps.changelog.outputs.tag }}
          name: ${{ steps.changelog.outputs.tag }}
          body: ${{ steps.changelog.outputs.clean_changelog }}
          files: |
            LICENSE.md
            ./src-tauri/target/release/bundle/deb/*.deb
            ./src-tauri/target/release/bundle/appimage/*.AppImage
